In [1]:
import torch

In [37]:
a=torch.arange(15).reshape(3,5).to(dtype=torch.float16).requires_grad_()
b=torch.arange(15).reshape(3,5).to(dtype=torch.float16)
c=a*a+b*b*b

In [52]:
t=torch.ones(3,5)
t[:2,1:]=0
c.backward(t,retain_graph=True)
print(a.grad)
print(b.grad)

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [30.,  0.,  0.,  0.,  0.],
        [60., 66., 72., 78., 84.]], dtype=torch.float16)
None


In [39]:
print(a.grad_fn)
print(b.grad_fn)
print(c.grad_fn)

None
None


In [40]:
print(a.is_leaf)
print(b.is_leaf)
print(c.is_leaf)

True
True
False


In [62]:
a=torch.arange(15).reshape(3,5).to(dtype=torch.float16).requires_grad_()
b=torch.arange(15).reshape(3,5).to(dtype=torch.float16)
c=a*a+b*b*b
c.backward(torch.ones(3,5))
print(a.grad)
print(b.grad)
a.grad.zero_()
c=a*a+b*b*b
c.backward(torch.ones(3,5))
print(a.grad)
print(b.grad)

tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.]], dtype=torch.float16)
None
tensor([[ 0.,  2.,  4.,  6.,  8.],
        [10., 12., 14., 16., 18.],
        [20., 22., 24., 26., 28.]], dtype=torch.float16)
None


True True


AttributeError: 'NoneType' object has no attribute 'requires_grad_'

In [12]:
a=torch.arange(15).reshape(3,5).to(dtype=torch.float16).requires_grad_()
print(a[:2,3:])

tensor([[3., 4.],
        [8., 9.]], dtype=torch.float16, grad_fn=<SliceBackward0>)
